# Generated by Django 4.2.4 on 2023-11-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_b64',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='blank.jpg', upload_to='pics'),
        ),
    ]
