# Generated by Django 4.2.4 on 2023-11-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_picture_b64_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_b64',
            field=models.TextField(blank=True),
        ),
    ]
