# Generated by Django 4.2.4 on 2023-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_picture_b64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_b64',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
