# Generated by Django 4.2.4 on 2023-11-05 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_field', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('agenda', models.TextField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.TimeField()),
                ('place', models.TextField()),
                ('attached_file', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('order', models.CharField(choices=[('H', 'high'), ('M', 'medium'), ('L', 'low')], max_length=1)),
                ('description', models.TextField()),
                ('message', models.TextField()),
                ('hosts', models.ManyToManyField(related_name='hosts', to=settings.AUTH_USER_MODEL)),
                ('participatins', models.ManyToManyField(related_name='participatins', to=settings.AUTH_USER_MODEL)),
                ('presents', models.ManyToManyField(related_name='presents', to=settings.AUTH_USER_MODEL)),
                ('related_sessions', models.ManyToManyField(blank=True, to='sessionn.session')),
            ],
        ),
    ]
