# Generated by Django 4.2.4 on 2023-11-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attached_file',
        ),
        migrations.AddField(
            model_name='session',
            name='attachfile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='sessionn.geeksmodel'),
            preserve_default=False,
        ),
    ]
