# Generated by Django 4.2.4 on 2023-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0002_remove_session_attached_file_session_attachfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.FileField(upload_to=''),
        ),
    ]
