# Generated by Django 4.2.4 on 2023-11-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0003_alter_geeksmodel_geeks_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='attachfile',
        ),
        migrations.AddField(
            model_name='session',
            name='attachfile',
            field=models.ManyToManyField(related_name='attachfile', to='sessionn.geeksmodel'),
        ),
    ]
