# Generated by Django 4.2.4 on 2023-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0005_alter_session_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='order',
            field=models.CharField(choices=[('1', 'order1'), ('2', 'order2'), ('3', 'order3'), ('4', 'order4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.TimeField(),
        ),
    ]
