# Generated by Django 4.2.4 on 2023-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0006_alter_session_order_alter_session_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.TimeField(auto_now=True),
        ),
    ]
