# Generated by Django 4.2.4 on 2023-11-12 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessionn', '0008_alter_session_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='geeks_field',
            field=models.FileField(blank=True, null=True, upload_to='attachedfiles'),
        ),
        migrations.AlterField(
            model_name='session',
            name='attachfile',
            field=models.ManyToManyField(null=True, related_name='attachfile', to='sessionn.geeksmodel'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hosts',
            field=models.ManyToManyField(null=True, related_name='hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='presents',
            field=models.ManyToManyField(null=True, related_name='presents', to=settings.AUTH_USER_MODEL),
        ),
    ]
