# Generated by Django 4.2.4 on 2023-11-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessionn', '0009_alter_geeksmodel_geeks_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attachfile',
            field=models.ManyToManyField(blank=True, related_name='attachfile', to='sessionn.geeksmodel'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='presents',
            field=models.ManyToManyField(blank=True, related_name='presents', to=settings.AUTH_USER_MODEL),
        ),
    ]
