# Generated by Django 4.2.4 on 2023-11-12 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0010_alter_session_attachfile_alter_session_hosts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='order',
            field=models.CharField(choices=[('1', 'order1'), ('2', 'order2'), ('3', 'order3'), ('4', 'order4')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
