# Generated by Django 4.2.4 on 2023-11-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0011_alter_session_order_alter_session_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='agenda',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='place',
            field=models.TextField(null=True),
        ),
    ]
