# Generated by Django 4.2.4 on 2023-11-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0012_alter_session_agenda_alter_session_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
    ]
