# Generated by Django 4.2.4 on 2023-12-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0013_alter_session_agenda_alter_session_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
