# Generated by Django 4.2.4 on 2023-12-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0014_session_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_archived',
        ),
    ]
