# Generated by Django 4.2.4 on 2023-12-11 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessionn', '0015_remove_session_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='participatins',
            field=models.ManyToManyField(blank=True, related_name='participatins', to=settings.AUTH_USER_MODEL),
        ),
    ]
