# Generated by Django 4.2.4 on 2023-12-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionn', '0016_alter_session_participatins'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_start',
            field=models.TimeField(null=True),
        ),
    ]
